In [3]:
import numpy as np

array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array)#numpy生成的array
print(array.dtype)#每个元素的类型
print("number of dim", array.ndim)# array的维度
print('shape:', array.shape)#形状，　两行三列。
print('size:', array.size)#array的大小＝array中所有元素的个数

[[1 2 3]
 [2 3 4]]
int32
number of dim 2
shape: (2, 3)
size: 6


In [4]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [7]:
a3 = np.empty((3,4),dtype = np.float)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [10]:
a2 = np.ones((3,4),dtype = np.int16)
print(a2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a4 = np.arange(10,20,2)
a4

array([10, 12, 14, 16, 18])

In [13]:
a5 = np.arange(12).reshape((3,4))
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a6 = np.linspace(1,10,4).reshape((2,2))
print(a6)

[[ 1.  4.]
 [ 7. 10.]]
