In [1]:
import numpy as np

In [ ]:
array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array)#numpy生成的array
print(array.dtype)#每个元素的类型
print("number of dim", array.ndim)# array的维度
print('shape:', array.shape)#形状，　两行三列。
print('size:', array.size)#array的大小＝array中所有元素的个数

In [4]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [7]:
a3 = np.empty((3,4),dtype = np.float)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [10]:
a2 = np.ones((3,4),dtype = np.int16)
print(a2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a4 = np.arange(10,20,2) #步长
a4

array([10, 12, 14, 16, 18])

In [13]:
a5 = np.arange(12).reshape((3,4))
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a6 = np.linspace(1,10,4).reshape((2,2)) #个数
print(a6)

[[ 1.  4.]
 [ 7. 10.]]


In [3]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print("a:",a)
print("b:",b)
c = a + b
print("c:",c)
c1 = a - b
print("c1:",c1)


a: [10 20 30 40]
b: [0 1 2 3]
c: [10 21 32 43]
c1: [10 19 28 37]


In [5]:
aa = np.array([[1,2,3,4],
              [11,22,33,44]])
bb = np.arange(4)
print("aa:", aa)
print("bb:", bb)
print("a+b:", aa+bb)

aa: [[ 1  2  3  4]
 [11 22 33 44]]
bb: [0 1 2 3]
a+b: [[ 1  3  5  7]
 [11 23 35 47]]


In [6]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c2 = b**2  # 平方
print("c2:", c2)
c3 = 10*np.sin(a)
print("c3:", c3)
print("b:", b)
print("b:", b < 3) #　b中小于３的都为TRUE
print("b:", b == 3) # b中等于３的为TRUE

c2: [0 1 4 9]
c3: [-5.44021111  9.12945251 -9.88031624  7.4511316 ]
b: [0 1 2 3]
b: [ True  True  True False]
b: [False False False  True]


In [7]:
d = np.array([[1, 2],
             [3, 4]])
e = np.arange(1, 8, 2).reshape((2, 2))
print("d:", d)
print("e:", e)
print(np.dot(d, e))
print(d.dot(e))

d: [[1 2]
 [3 4]]
e: [[1 3]
 [5 7]]
[[11 17]
 [23 37]]
[[11 17]
 [23 37]]


In [5]:
#随机数
f = np.random.random((2,4))
print(f)
print(np.sum(f))
print(sum(f))
print(np.min(f))
print("="*10)
print(np.sum(f, axis=0))
print(np.min(f, axis=1))
print(np.max(f, axis=0))

[[0.48706364 0.83402375 0.87794169 0.08789477]
 [0.83136976 0.83819156 0.88011567 0.13606005]]
4.972660874225259
[1.31843339 1.67221531 1.75805735 0.22395482]
0.08789477000240553
[1.31843339 1.67221531 1.75805735 0.22395482]
[0.08789477 0.13606005]
[0.83136976 0.83819156 0.88011567 0.13606005]


In [8]:
c = np.arange(14, 2, -1).reshape((3, 4))
print(c)
print("sort:", np.sort(c))
print(c.T)
print("clip:",np.clip(c, 5, 9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
sort: [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [4]:
a = np.arange(2, 14).reshape((3, 4))
print("a:",a)
print("average:",np.average(a))
print("median:",np.median(a))
print("cumsum:", np.cumsum(a))
print("diff:", np.diff(a))

a: [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
average: 7.5
median: 7.5
cumsum: [ 2  5  9 14 20 27 35 44 54 65 77 90]
diff: [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [2]:
a = np.array([[2, 6, 0, 4],
             [4, 8, 9, 1],
             [10, 2, 3, 11]])
print("argmin:", np.argmin(a))
print("axis0:", np.argmin(a, axis=0))
print("axis1:", np.argmin(a, axis=1))
print("argmax:", np.argmax(a))
print("zero:", np.nonzero(a))
'''
argmin/argmax都是返回最小值/最大值的索引的函数
'''

argmin: 2
axis0: [0 2 0 1]
axis1: [2 3 1]
argmax: 11
zero: (array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


'\nargmin/argmax都是返回最小值/最大值的索引的函数\n'

In [4]:
a = np.arange(3, 15).reshape((3, 4))
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [10]:
print(a[1])
print(a[:][1])
print(a[:][1])#索引为1的行，同上
print(a[2][1])#和数组一样的表示 
print(a[2, 1])#同上，这才是比较标准的array的索引表示，前面是行后面是列的索引
print(a[:, 1])#索引为１的列,生成为行向量
print(a[:, 1:2])#索引为１的列，生成为列向量
print(a[:, 1:3])
print(a[1, 1:3])#为上面a[:, 1:3]的索引为１的行向量

[ 7  8  9 10]
[ 7  8  9 10]
[ 7  8  9 10]
12
12
[ 4  8 12]
[[ 4]
 [ 8]
 [12]]
[[ 4  5]
 [ 8  9]
 [12 13]]
[8 9]


In [5]:
a = np.arange(3, 15).reshape((3, 4))# 数据都是下取上差一个取到。
print(a)
print("row")
for row in a:
    print(row)
print("column")
for column in a.T:
    print(column)

print("="*50)
print(a.flatten())#所有元素变成yiwei
b = np.array([[1,2,3]])
print(b)
print(b.flatten())
for item in a.flat:
    print(item)






[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
row
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
column
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[[1 2 3]]
[1 2 3]
3
4
5
6
7
8
9
10
11
12
13
14


In [2]:
a = np.array([1, 1, 2])
b = np.array([2, 3, 4])

c = np.vstack(( a , b ))
print("a:",a)
print("b:",b)
print("c:",c)
print("a,c shape:",a.shape,c.shape)

d = np.hstack((a, b))
print("d:",d)
print(d.shape)
print(a.T)
print(a[np.newaxis, : ].shape)
print(a[ : ,np.newaxis].shape)
print(a[ : ,np.newaxis])


a: [1 1 2]
b: [2 3 4]
c: [[1 1 2]
 [2 3 4]]
a,c shape: (3,) (2, 3)
d: [1 1 2 2 3 4]
(6,)
[1 1 2]
(1, 3)
(3, 1)
[[1]
 [1]
 [2]]


In [4]:
a = np.array([1,1,2])[:,np.newaxis]
b = np.array([2,3,4])[:,np.newaxis]

c = np.concatenate((a,b,b),axis = 0)
print(c)
c = np.concatenate((a, b, b), axis=1) #多向量融合
print(c)

[[1]
 [1]
 [2]
 [2]
 [3]
 [4]
 [2]
 [3]
 [4]]
[[1 2 2]
 [1 3 3]
 [2 4 4]]


In [3]:
a = np.arange(12).reshape((3,4))
print(a)
print("equally separate")
print("vertical:",np.split(a, 2, axis = 1))
print("horizontal:",np.split(a,3, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
equally separate
vertical: [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
horizontal: [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [4]:
#unequal
print(np.array_split(a,3,axis = 1))
print("vertical_a:",np.vsplit(a,3))
print("horizontal_a:",np.hsplit(a,2))


[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
vertical_a: [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
horizontal_a: [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
