In [3]:
import numpy as np

array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array)#numpy生成的array
print(array.dtype)#每个元素的类型
print("number of dim", array.ndim)# array的维度
print('shape:', array.shape)#形状，　两行三列。
print('size:', array.size)#array的大小＝array中所有元素的个数

[[1 2 3]
 [2 3 4]]
int32
number of dim 2
shape: (2, 3)
size: 6


In [4]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [7]:
a3 = np.empty((3,4),dtype = np.float)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a1 = np.zeros((2,3),dtype = np.int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [10]:
a2 = np.ones((3,4),dtype = np.int16)
print(a2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a4 = np.arange(10,20,2) #步长
a4

array([10, 12, 14, 16, 18])

In [13]:
a5 = np.arange(12).reshape((3,4))
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a6 = np.linspace(1,10,4).reshape((2,2)) #个数
print(a6)

[[ 1.  4.]
 [ 7. 10.]]


In [3]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print("a:",a)
print("b:",b)
c = a + b
print("c:",c)
c1 = a - b
print("c1:",c1)


a: [10 20 30 40]
b: [0 1 2 3]
c: [10 21 32 43]
c1: [10 19 28 37]


In [5]:
aa = np.array([[1,2,3,4],
              [11,22,33,44]])
bb = np.arange(4)
print("aa:", aa)
print("bb:", bb)
print("a+b:", aa+bb)

aa: [[ 1  2  3  4]
 [11 22 33 44]]
bb: [0 1 2 3]
a+b: [[ 1  3  5  7]
 [11 23 35 47]]


In [6]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c2 = b**2  # 平方
print("c2:", c2)
c3 = 10*np.sin(a)
print("c3:", c3)
print("b:", b)
print("b:", b < 3) #　b中小于３的都为TRUE
print("b:", b == 3) # b中等于３的为TRUE

c2: [0 1 4 9]
c3: [-5.44021111  9.12945251 -9.88031624  7.4511316 ]
b: [0 1 2 3]
b: [ True  True  True False]
b: [False False False  True]


In [7]:
d = np.array([[1, 2],
             [3, 4]])
e = np.arange(1, 8, 2).reshape((2, 2))
print("d:", d)
print("e:", e)
print(np.dot(d, e))
print(d.dot(e))

d: [[1 2]
 [3 4]]
e: [[1 3]
 [5 7]]
[[11 17]
 [23 37]]
[[11 17]
 [23 37]]
